import { type RouteConfig, index, layout, route } from "@react-router/dev/routes";

export default [
  layout("routes/_app.tsx", [
    index("routes/_app._index.tsx"),
    route("settings",                          "routes/_app.settings._index.tsx"),
    route("settings/currencies",              "routes/_app.settings.currencies.tsx"),
    route("settings/currencies/new",          "routes/_app.settings.currencies.new.tsx"),
    route("settings/currencies/:id/edit",     "routes/_app.settings.currencies.$id.edit.tsx"),
    route("settings/tags",                    "routes/_app.settings.tags.tsx"),
    route("settings/tags/new",                "routes/_app.settings.tags.new.tsx"),
    route("settings/tags/:id/edit",           "routes/_app.settings.tags.$id.edit.tsx"),
    route("settings/preferences",             "routes/_app.settings.preferences.tsx"),
    route("settings/snapshots",               "routes/_app.settings.snapshots.tsx"),
    route("accounts",           "routes/_app.accounts._index.tsx"),
    route("accounts/new",       "routes/_app.accounts.new.tsx"),
    route("accounts/:id",       "routes/_app.accounts.$id.tsx"),
    route("transactions",             "routes/_app.transactions._index.tsx"),
    route("transactions/new",         "routes/_app.transactions.new.tsx"),
    route("transactions/:id",         "routes/_app.transactions.$id.tsx"),
    route("reports/balance-sheet",    "routes/_app.reports.balance-sheet.tsx"),
    route("reports/income",           "routes/_app.reports.income.tsx"),
    route("reports/net-worth",        "routes/_app.reports.net-worth.tsx"),
    route("reports/spending",         "routes/_app.reports.spending.tsx"),
    route("reports/securities",       "routes/_app.reports.securities.tsx"),
  ]),
  route("login",  "routes/login.tsx"),
  route("logout", "routes/logout.tsx"),
  // REST API
  route("api/docs",                          "routes/api.docs.ts"),
  route("api/v1/openapi.json",               "routes/api.v1.openapi.ts"),
  route("api/v1/accounts",                   "routes/api.v1.accounts._index.ts"),
  route("api/v1/accounts/:id",               "routes/api.v1.accounts.$id.ts"),
  route("api/v1/transactions",               "routes/api.v1.transactions._index.ts"),
  route("api/v1/transactions/:id",           "routes/api.v1.transactions.$id.ts"),
  route("api/v1/currencies",                 "routes/api.v1.currencies._index.ts"),
  route("api/v1/currencies/:id",             "routes/api.v1.currencies.$id.ts"),
  route("api/v1/tags",                       "routes/api.v1.tags._index.ts"),
  route("api/v1/tags/:id",                   "routes/api.v1.tags.$id.ts"),
  route("api/v1/reports/balance-sheet",      "routes/api.v1.reports.balance-sheet.ts"),
  route("api/v1/reports/income",             "routes/api.v1.reports.income.ts"),
  route("api/v1/reports/net-worth",          "routes/api.v1.reports.net-worth.ts"),
  route("api/v1/reports/spending",           "routes/api.v1.reports.spending.ts"),
  route("api/v1/reports/securities",         "routes/api.v1.reports.securities.ts"),
] satisfies RouteConfig;
